# Build configuration for https://www.tea-ci.org

build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    #- pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-pkg-config
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-lua51

matrix:
  arch:
    - 64
    - 32
